### ISSUE TITLE
very slow scroll on mobile view

### ISSUE THREAD

**Issue by MosabWadea** [Openworx/backend_theme#15]
Hi
when I log into my odoo fro mobile the scrolling is very slow when I open the app drawer..

Please help to solve this

**Comment by totalard** [comment]
Yeah... Important... Me too

**Comment by mgielissen** [comment]
https://github.com/Openworx/backend_theme/pull/13

**Comment by lasley** [comment]
IIRC this one should be fixed as well. Can you confirm on the new version?

**Comment by MosabWadea** [comment]
@lasley I am afraid it is not solved, I have updated and installed the web_responsive module as well but still the same issue is there..

**Comment by lasley** [comment]
What Odoo version are you on? What browser and version?

Just to confirm - you're referring to the scrolling of the app icons in the app drawer right?

**Comment by MosabWadea** [comment]
yes I am referring to the scrolling of the app icons in the app drawer from mobile

system: android oreo
browser: chrome
odoo V 10.0.2

**Comment by MosabWadea** [comment]
please check the video here to see what I am referring to https://youtu.be/ndTXHe-E694

**Comment by lasley** [comment]
Thanks for the additional info @MosabWadea. 

I can't replicate this on iPhone, but it looks like whatever it is does replicate in Chrome's emulator. It's in `web_responsive`, so I made OCA/web#741

**Comment by mgielissen** [comment]
Scrolling works good with iPhone and slow with Android/Chrome

**Comment by mgielissen** [comment]
This PR fixes the problem https://github.com/OCA/web/pull/742
